name = "Cobbleverse-Serial"
author = "AndroMailo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a2692220ad66514e0de6085b00b8a754ea4fc83ad82d6dde3af73284b60e685"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
